// flow-typed signature: ce745dab9d24e90368585bf428dc468a
// flow-typed version: <<STUB>>/http_v^0.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
